# MP1 · Prompt Lab — Compare LLM Strategies on a Task

**Starter template.** Fill in the TODOs. ~5-8 hours over 3 days.

Read `learner/MP1_Brief.md` before starting if you haven't already.

---

## Setup

In [2]:
import asyncio
import json
import os
import time
from pathlib import Path

import pandas as pd
from openai import AsyncOpenAI

# Make sure your OPENAI_API_KEY is set in the environment
assert os.environ.get('OPENAI_API_KEY'), 'Set OPENAI_API_KEY first'

client = AsyncOpenAI()

MODEL = 'gpt-4o-mini'
JUDGE_MODEL = 'gpt-4o'
TEMPERATURE = 0.0

# Cost rates ($ per token) — from W4 cost.py
RATES = {
    'gpt-4o-mini': {'in': 0.15 / 1_000_000, 'out': 0.60 / 1_000_000},
    'gpt-4o':      {'in': 2.50 / 1_000_000, 'out': 10.00 / 1_000_000},
}

print('Setup complete.')

Setup complete.

## Step 1 — Load the data

In [3]:
DATA_DIR = Path('../data')   # adjust if your folder layout differs

snippets = {
    row['id']: row 
    for row in (json.loads(line) for line in (DATA_DIR / 'job_snippets.jsonl').read_text().splitlines() if line.strip())}
golden = {
    row['id']: row 
    for row in (json.loads(line) for line in (DATA_DIR / 'golden_set.jsonl').read_text().splitlines() if line.strip())}

print(f'Loaded {len(snippets)} snippets, {len(golden)} golden entries.')
print('Sample snippet:', snippets)

Loaded 10 snippets, 10 golden entries.
Sample snippet: {'j01': {'id': 'j01', 'snippet': 'Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.'}, 'j02': {'id': 'j02', 'snippet': "We're looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred."}, 'j03': {'id': 'j03', 'snippet': "Globex International seeks a Product Manager - Growth. You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts."}, 'j04': {'id': 'j04', 'snippet': 'Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.'}, 'j05': {'id': 'j05', 'snippet': 'Hooli is looking for a Junior Frontend Developer. Fresh grads welcome — no prior experience required. We care about curiosity and willingness to learn. JavaScript, React, and CSS fundamentals expected.'}, 'j06': {'id': 'j06', 'snippet': 'Pied Piper Inc. has an opening for a Senior ML Engineer. Compression algorithms background a plus. We typically look for 7+ years in production ML and distributed systems, but exceptional candidates with less are welcome.'}, 'j07': {'id': 'j07', 'snippet': "We want a builder. Soylent Industries is growing fast. The role is Engineering Manager. About three years leading engineering teams, plus a solid IC background before that. Apply if you've shipped real products."}, 'j08': {'id': 'j08', 'snippet': "Senior UX Researcher at Wonka Confectionery Ltd. You'll design and run user studies for our digital storefront. Five years of UX research experience or equivalent portfolio required."}, 'j09': {'id': 'j09', 'snippet': 'Stark Industries: Cybersecurity Analyst (mid-level). Three to five years in a SOC environment or equivalent. Familiarity with SIEM tools, incident response runbooks, and basic threat modelling.'}, 'j10': {'id': 'j10', 'snippet': "Cyberdyne Systems is hiring. Role: AI/ML Research Scientist. PhD preferred but not required. Strong publication record in deep learning or reinforcement learning. We don't list a specific years requirement — we hire on demonstrated impact."}}

In [4]:
golden

{'j01': {'id': 'j01',
  'company': 'Acme Corp',
  'role': 'Senior Software Engineer',
  'years_experience_required': 5,
  'notes': 'clean — clear company + role + years'},
 'j02': {'id': 'j02',
  'company': 'Northwind Ltd',
  'role': 'Data Analyst',
  'years_experience_required': 2,
  'notes': 'clean — preferred used but still a stated minimum'},
 'j03': {'id': 'j03',
  'company': 'Globex International',
  'role': 'Product Manager - Growth',
  'years_experience_required': 4,
  'notes': "clean — 'at least 4 years'"},
 'j04': {'id': 'j04',
  'company': 'Initech',
  'role': 'Lead DevOps Engineer',
  'years_experience_required': 6,
  'notes': "slightly fuzzy — 'around 6 years' — accept 6"},
 'j05': {'id': 'j05',
  'company': 'Hooli',
  'role': 'Junior Frontend Developer',
  'years_experience_required': 0,
  'notes': 'edge — fresh grads OK = 0 years'},
 'j06': {'id': 'j06',
  'company': 'Pied Piper Inc.',
  'role': 'Senior ML Engineer',
  'years_experience_required': 7,
  'notes': "fuzzy — '7+ years' typically taken as 7; exceptional candidates clause is colour text"},
 'j07': {'id': 'j07',
  'company': 'Soylent Industries',
  'role': 'Engineering Manager',
  'years_experience_required': 3,
  'notes': "spelled-out number — 'about three years' → 3"},
 'j08': {'id': 'j08',
  'company': 'Wonka Confectionery Ltd',
  'role': 'Senior UX Researcher',
  'years_experience_required': 5,
  'notes': "clean — 'five years' → 5"},
 'j09': {'id': 'j09',
  'company': 'Stark Industries',
  'role': 'Cybersecurity Analyst',
  'years_experience_required': 3,
  'notes': "range 3-5 — take the minimum, 3. Accept 3 or 'between 3 and 5'."},
 'j10': {'id': 'j10',
  'company': 'Cyberdyne Systems',
  'role': 'AI/ML Research Scientist',
  'years_experience_required': None,
  'notes': 'edge — no years stated. Correct answer: null. Penalise if model fabricates a number.'}}

In [5]:
snippets

{'j01': {'id': 'j01',
  'snippet': 'Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.'},
 'j02': {'id': 'j02',
  'snippet': "We're looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred."},
 'j03': {'id': 'j03',
  'snippet': "Globex International seeks a Product Manager - Growth. You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts."},
 'j04': {'id': 'j04',
  'snippet': 'Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.'},
 'j05': {'id': 'j05',
  'snippet': 'Hooli is looking for a Junior Frontend Developer. Fresh grads welcome — no prior experience required. We care about curiosity and willingness to learn. JavaScript, React, and CSS fundamentals expected.'},
 'j06': {'id': 'j06',
  'snippet': 'Pied Piper Inc. has an opening for a Senior ML Engineer. Compression algorithms background a plus. We typically look for 7+ years in production ML and distributed systems, but exceptional candidates with less are welcome.'},
 'j07': {'id': 'j07',
  'snippet': "We want a builder. Soylent Industries is growing fast. The role is Engineering Manager. About three years leading engineering teams, plus a solid IC background before that. Apply if you've shipped real products."},
 'j08': {'id': 'j08',
  'snippet': "Senior UX Researcher at Wonka Confectionery Ltd. You'll design and run user studies for our digital storefront. Five years of UX research experience or equivalent portfolio required."},
 'j09': {'id': 'j09',
  'snippet': 'Stark Industries: Cybersecurity Analyst (mid-level). Three to five years in a SOC environment or equivalent. Familiarity with SIEM tools, incident response runbooks, and basic threat modelling.'},
 'j10': {'id': 'j10',
  'snippet': "Cyberdyne Systems is hiring. Role: AI/ML Research Scientist. PhD preferred but not required. Strong publication record in deep learning or reinforcement learning. We don't list a specific years requirement — we hire on demonstrated impact."}}

## Step 2 — Write the four prompt strategies

Each strategy is a function that takes a snippet text and returns the messages list to send to the LLM.

Implement all four. Keep each one focused — the point is to *see* the difference between strategies, not to over-engineer any one.

**TODO:** fill in the four `prompt_*` functions below.

In [6]:
def prompt_zero_shot(snippet_text: str) -> list[dict]:
    """Strategy 1 — zero-shot. Just ask, no examples, no persona."""
    # TODO: return a messages list like [{'role': 'user', 'content': '...'}]
    try: 
        content = (
        "Extract job details from the following job snippet with these keys:\n"
        '1.company, 2.role, 3.years_experience_required as integer, 4.notes'
        "Output valid JSON with no markdown code.\n\n"
        f'Input Snippet: "{snippet_text}"' )
        return [{'role': 'user', 'content': content}]
    except E:
        print(f"Exception: {e}")
    


def prompt_few_shot(snippet_text: str) -> list[dict]:
    """Strategy 2 — few-shot. Include 2-3 worked examples in the prompt."""
    # TODO: same shape, but include examples
    try: 
        content = (
        "Extract job details from the following job snippet with these keys:\n"
        '1.company, 2.role, 3.years_experience_required as integer, 4.notes'
        'Example 1:\n'
        'Input: "Globex International seeks a Senior Engineer with 5+ years of experience, joining timeframe immediate"\n'
        'Output: {"company": "Globex International", "role": "Senior Engineer", "years_experience_required": 5, "notes": "Software Engineer, Immediate joining."}\n\n'
        'Example 2:\n'
        'Input: "We want a tester, ~3 years in software testing, for our stealth startup."\n'
        'Output: {"company": "Unknown", "role": "Software Tester", "years_experience_required": 3, "notes": "Software Tester for sleath startup."}\n\n'
        'Example 3\n'
        'Input: "Looking for person for Sales Manager role on fastest growing company. The role will be inone of the Reliance Group of compaies."\n'
        'Output: {"company": "Reliance Group", "role": "Sales Manager", "years_experience_required": null, "notes": "Looking for Sales maanger position, since manager position might require 10+ years experience."}\n\n'
        f'Input snippet:\n"{snippet_text}"\n\n'
        "Output valid JSON with no markdown code.\n\n")
        return [{'role': 'user', 'content': content}]
    except E:
        print(f"Exception: {e}")
    


def prompt_structured(snippet_text: str) -> list[dict]:
    """Strategy 3 — structured / role-based. Use a system prompt with a persona and explicit JSON schema."""
    # TODO: 'You are an expert recruiter... Output JSON with these exact fields...'
    try:
        content = (
        "You are an expert data extraction assistant. Extract job requirements "
        "from the text into a JSON object strictly matching this structural specification:\n\n"
        "EXPECTED JSON SCHEMA:\n"
        "{\n"
        '  "company": string,                   // Canonical company name, or "Unknown"\n'
        '  "role": string,                      // Specific job title\n'
        '  "years_experience_required": int|null, // Integer >= 0, or null if unspecified/ambiguous\n'
        '  "notes": string                      // Explicit justification for nulls or extracted ranges\n'
        "}\n\n"
        "FIELD RULES:\n"
        "- For years of experience extract one integer lowest from the range\n"
        "- If experience is not specified set years_experience_required to null.\n"
        "- Do not guess company names if not explicitly mentioned.\n\n"
        "- Company name, set to 'Unknown' if missing"
        f'Input Snippet:\n"{snippet_text}"\n\n'
        "Output valid JSON with no markdown code.\n\n"
        )
        return [{"role": "user", "content": content}]
    except E:
        print(f"Exception: {e}")



def prompt_cot(snippet_text: str) -> list[dict]:
    """Strategy 4 — chain-of-thought. Ask the model to reason before answering."""
    # TODO: 'Think step by step, then answer with JSON.'
    try:
        content = (
                "Extract job details from the snippet with keys: "
                '"company", "role", "years_experience_required", and "notes".\n\n'
                "Follow these steps before producing the output:\n"
                "1. Identify the company name (set to 'Unknown' if missing).\n"
                "2. Identify the role/job title.\n"
                "3. Extract required years of experience as an integer (or null if missing).\n"
                "4. Why this is done into 'notes' field.\n\n"
                f'Input Snippet: "{snippet_text}"\n\n'
                "Output valid JSON with no markdown code.\n\n:"
            )
        return [{"role": "user", "content": content}]
    except E:
        print(f"Exception: {e}")


STRATEGIES = {
    'zero_shot': prompt_zero_shot,
    'few_shot': prompt_few_shot,
    'structured': prompt_structured,
    'cot': prompt_cot,
}

In [7]:
resp = prompt_few_shot('Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.')
print(f"Prompt_few_shot: {resp}")
resp = prompt_zero_shot('Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.')
print(f"Prompt_Zero_shot: {resp}")
resp = prompt_structured('Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.')
print(f"prompt_structured: {resp}")
resp = prompt_cot('Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.')
print(f"prompt_cot: {resp}")

Prompt_few_shot: [{'role': 'user', 'content': 'Extract job details from the following job snippet with these keys:\n1.company, 2.role, 3.years_experience_required as integer, 4.notesExample 1:\nInput: "Globex International seeks a Senior Engineer with 5+ years of experience, joining timeframe immediate"\nOutput: {"company": "Globex International", "role": "Senior Engineer", "years_experience_required": 5, "notes": "Software Engineer, Immediate joining."}\n\nExample 2:\nInput: "We want a tester, ~3 years in software testing, for our stealth startup."\nOutput: {"company": "Unknown", "role": "Software Tester", "years_experience_required": 3, "notes": "Software Tester for sleath startup."}\n\nExample 3\nInput: "Looking for person for Sales Manager role on fastest growing company. The role will be inone of the Reliance Group of compaies."\nOutput: {"company": "Reliance Group", "role": "Sales Manager", "years_experience_required": null, "notes": "Looking for Sales maanger position, since manager position might require 10+ years experience."}\n\nInput snippet:\n"Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD."\n\nOutput valid JSON with no markdown code.\n\n'}]
Prompt_Zero_shot: [{'role': 'user', 'content': 'Extract job details from the following job snippet with these keys:\n1.company, 2.role, 3.years_experience_required as integer, 4.notesOutput valid JSON with no markdown code.\n\nInput Snippet: "Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD."'}]
prompt_structured: [{'role': 'user', 'content': 'You are an expert data extraction assistant. Extract job requirements from the text into a JSON object strictly matching this structural specification:\n\nEXPECTED JSON SCHEMA:\n{\n  "company": string,                   // Canonical company name, or "Unknown"\n  "role": string,                      // Specific job title\n  "years_experience_required": int|null, // Integer >= 0, or null if unspecified/ambiguous\n  "notes": string                      // Explicit justification for nulls or extracted ranges\n}\n\nFIELD RULES:\n- For years of experience extract one integer lowest from the range\n- If experience is not specified set years_experience_required to null.\n- Do not guess company names if not explicitly mentioned.\n\n- Company name, set to \'Unknown\' if missingInput Snippet:\n"Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD."\n\nOutput valid JSON with no markdown code.\n\n'}]
prompt_cot: [{'role': 'user', 'content': 'Extract job details from the snippet with keys: "company", "role", "years_experience_required", and "notes".\n\nFollow these steps before producing the output:\n1. Identify the company name (set to \'Unknown\' if missing).\n2. Identify the role/job title.\n3. Extract required years of experience as an integer (or null if missing).\n4. Why this is done into \'notes\' field.\n\nInput Snippet: "Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD."\n\nOutput valid JSON with no markdown code.\n\n:'}]

## Step 3 — Async batching

Run all 10 snippets × 4 strategies = 40 calls in parallel.

Capture for each call: strategy, snippet_id, raw response, parsed extraction, cost, latency.

**TODO:** implement `run_one` (single call) and `run_all` (batch all 40).

In [ ]:
import sys
import importlib
from pathlib import Path
import json
from types import SimpleNamespace
from pydantic import BaseModel
import time

class Answer(BaseModel):
    question: str
    text:     str
    cost_usd: float
    retries:  int = 0
    confidence: float = 1.0
    sources: list[str] = []
    prompt_tokens: int
    completion_tokens: int

# Add project root directory to sys.path
#ROOT_DIR = Path(__file__).resolve().parents[3]

ROOT_DIR = Path.cwd().parents[3]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

# Dynamically import the pipeline module using the exact directory name string
pipeline_module = importlib.import_module("IITM-AI-RAG.src.pipeline.pipeline")

_pipeline_ask_llm = pipeline_module.ask_llm
_pipeline_stream = pipeline_module.stream_answer

def parse_response(text: str | dict) -> int | None:
    """Try to parse a JSON object out of the model's response. Return None if it doesn't parse.
    
    Hint: models sometimes wrap JSON in ```json ... ``` fences. Strip them first.
    """
    # TODO: extract + parse the JSON, return a dict or None
    # Doing this as I've called pipeline.ask_llm and the result is returned as dict
    try:
        if isinstance(text, dict):
            return 1
        else:
            return 0
           # always parses now
        
    except:
        return  0


async def run_one(strategy_name: str, snippet: dict, snipID: str) -> dict:
    """Run one strategy on one snippet. Return a dict with all the captured fields."""
    # TODO: call the model, time the call, compute cost, parse the response
    question = STRATEGIES[strategy_name](snippet)
    content = SimpleNamespace(text=str(question[0]['content']))
    start_time = time.perf_counter()
    try:    
        response = await _pipeline_ask_llm(content) #Calling the function built within src.pipeline.pipeline = have attached the code in .MD
        response_dump = response.model_dump()
    except:
        response_dump = ""
    parse_status = parse_response(response_dump)
    if parse_status == 0:
        response_dump ={"text": "{}"}
    latency_s = time.perf_counter() - start_time
    #print(f"Response: {response} \n\n")
    response_dump["snippet_id"] = snipID
    response_dump["strategy"] = strategy_name
    response_dump["latency"] = latency_s
    response_dump['parse_status'] = parse_status
    print(f"Response: {response_dump} \n\n")
    return response_dump
    

async def run_all() -> list[dict]:
    """Run all 10 × 4 = 40 calls in parallel. Use asyncio.gather."""
    # TODO: build the task list, gather, return results
    tasks = []
    for item in snippets.values():
        print('Snippet {item}')
        for strategy in STRATEGIES.keys():
            tasks.append(run_one(strategy, item["snippet"], item["id"]))
            ##break
        ##break
    results = await asyncio.gather(*tasks)
    return results
    #raise NotImplementedError

In [9]:
# Run it
results = await run_all()
print(f'Got {len(results)} results.')
print(f"Results: {results}")
results[0]

Snippet {item}
Snippet {item}
Snippet {item}
Snippet {item}
Snippet {item}
Snippet {item}
Snippet {item}
Snippet {item}
Snippet {item}
Snippet {item}

Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_ZcnieZ1C9lqO0KjLK7WEOoVT', function=Function(arguments='{"content":"{\\"company\\": \\"Northwind Ltd.\\", \\"role\\": \\"Data Analyst\\", \\"years_experience_required\\": 2, \\"notes\\": \\"2 years minimum experience preferred.\\"}","confidence":0.95,"sources":[],"prompt_tokens":39,"completion_tokens":216}', name='answer_question'), type='function')]))
structured args: {'content': '{"company": "Northwind Ltd.", "role": "Data Analyst", "years_experience_required": 2, "notes": "2 years minimum experience preferred."}', 'confidence': 0.95, 'sources': [], 'prompt_tokens': 39, 'completion_tokens': 216}
confidence (from the MODEL): 0.95
Response: {'question': 'Extract job details from the snippet with keys: "company", "role", "years_experience_required", and "notes".\n\nFollow these steps before producing the output:\n1. Identify the company name (set to \'Unknown\' if missing).\n2. Identify the role/job title.\n3. Extract required years of experience as an integer (or null if missing).\n4. Why this is done into \'notes\' field.\n\nInput Snippet: "We\'re looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you\'ll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred."\n\nOutput valid JSON with no markdown code.\n\n:', 'text': '{"company": "Northwind Ltd.", "role": "Data Analyst", "years_experience_required": 2, "notes": "2 years minimum experience preferred."}', 'cost_usd': 6.764999999999999e-05, 'retries': 0, 'confidence': 0.95, 'sources': [], 'prompt_tokens': 215, 'completion_tokens': 59, 'snippet_id': 'j02', 'strategy': 'cot', 'latency': 1.3859710979995725, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_P2buJBBSsSrdN7KONlhlCywb', function=Function(arguments='{"content":"{\\"company\\":\\"Globex International\\",\\"role\\":\\"Product Manager - Growth\\",\\"years_experience_required\\":4,\\"notes\\":\\"Experience required is explicitly stated as at least 4 years.\\"}","confidence":0.95,"sources":[],"prompt_tokens":99,"completion_tokens":194}', name='answer_question'), type='function')]))
structured args: {'content': '{"company":"Globex International","role":"Product Manager - Growth","years_experience_required":4,"notes":"Experience required is explicitly stated as at least 4 years."}', 'confidence': 0.95, 'sources': [], 'prompt_tokens': 99, 'completion_tokens': 194}
confidence (from the MODEL): 0.95
Response: {'question': 'You are an expert data extraction assistant. Extract job requirements from the text into a JSON object strictly matching this structural specification:\n\nEXPECTED JSON SCHEMA:\n{\n  "company": string,                   // Canonical company name, or "Unknown"\n  "role": string,                      // Specific job title\n  "years_experience_required": int|null, // Integer >= 0, or null if unspecified/ambiguous\n  "notes": string                      // Explicit justification for nulls or extracted ranges\n}\n\nFIELD RULES:\n- For years of experience extract one integer lowest from the range\n- If experience is not specified set years_experience_required to null.\n- Do not guess company names if not explicitly mentioned.\n\n- Company name, set to \'Unknown\' if missingInput Snippet:\n"Globex International seeks a Product Manager - Growth. You\'ll own activation and onboarding metrics across our consumer apps. We\'re looking for someone with at least 4 years of product management experience in B2C contexts."\n\nOutput valid JSON with no markdown code.\n\n', 'text': '{"company":"Globex International","role":"Product Manager - Growth","years_experience_required":4,"notes":"Experience required is explicitly stated as at least 4 years."}', 'cost_usd': 7.86e-05, 'retries': 0, 'confidence': 0.95, 'sources': [], 'prompt_tokens': 288, 'completion_tokens': 59, 'snippet_id': 'j03', 'strategy': 'structured', 'latency': 1.3930429220017686, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_WMWX0fZ1W8bySGB0c7lEfX1l', function=Function(arguments='{"content":"{\\"company\\": \\"Soylent Industries\\", \\"role\\": \\"Engineering Manager\\", \\"years_experience_required\\": 3, \\"notes\\": \\"Experience specified as \'About three years leading engineering teams\'.\\"}","confidence":0.95,"sources":[],"prompt_tokens":0,"completion_tokens":0}', name='answer_question'), type='function')]))
structured args: {'content': '{"company": "Soylent Industries", "role": "Engineering Manager", "years_experience_required": 3, "notes": "Experience specified as \'About three years leading engineering teams\'."}', 'confidence': 0.95, 'sources': [], 'prompt_tokens': 0, 'completion_tokens': 0}
confidence (from the MODEL): 0.95
Response: {'question': 'You are an expert data extraction assistant. Extract job requirements from the text into a JSON object strictly matching this structural specification:\n\nEXPECTED JSON SCHEMA:\n{\n  "company": string,                   // Canonical company name, or "Unknown"\n  "role": string,                      // Specific job title\n  "years_experience_required": int|null, // Integer >= 0, or null if unspecified/ambiguous\n  "notes": string                      // Explicit justification for nulls or extracted ranges\n}\n\nFIELD RULES:\n- For years of experience extract one integer lowest from the range\n- If experience is not specified set years_experience_required to null.\n- Do not guess company names if not explicitly mentioned.\n\n- Company name, set to \'Unknown\' if missingInput Snippet:\n"We want a builder. Soylent Industries is growing fast. The role is Engineering Manager. About three years leading engineering teams, plus a solid IC background before that. Apply if you\'ve shipped real products."\n\nOutput valid JSON with no markdown code.\n\n', 'text': '{"company": "Soylent Industries", "role": "Engineering Manager", "years_experience_required": 3, "notes": "Experience specified as \'About three years leading engineering teams\'."}', 'cost_usd': 8.13e-05, 'retries': 0, 'confidence': 0.95, 'sources': [], 'prompt_tokens': 286, 'completion_tokens': 64, 'snippet_id': 'j07', 'strategy': 'structured', 'latency': 1.3875639569996565, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_ZGFi3H0BRsgQmJiciS3eS1C6', function=Function(arguments='{"content":"{\\"company\\": \\"Stark Industries\\", \\"role\\": \\"Cybersecurity Analyst\\", \\"years_experience_required\\": 3, \\"notes\\": \\"Experience is specified as a range of three to five years.\\"}","confidence":0.95,"sources":[],"prompt_tokens":97,"completion_tokens":197}', name='answer_question'), type='function')]))
structured args: {'content': '{"company": "Stark Industries", "role": "Cybersecurity Analyst", "years_experience_required": 3, "notes": "Experience is specified as a range of three to five years."}', 'confidence': 0.95, 'sources': [], 'prompt_tokens': 97, 'completion_tokens': 197}
confidence (from the MODEL): 0.95
Response: {'question': 'You are an expert data extraction assistant. Extract job requirements from the text into a JSON object strictly matching this structural specification:\n\nEXPECTED JSON SCHEMA:\n{\n  "company": string,                   // Canonical company name, or "Unknown"\n  "role": string,                      // Specific job title\n  "years_experience_required": int|null, // Integer >= 0, or null if unspecified/ambiguous\n  "notes": string                      // Explicit justification for nulls or extracted ranges\n}\n\nFIELD RULES:\n- For years of experience extract one integer lowest from the range\n- If experience is not specified set years_experience_required to null.\n- Do not guess company names if not explicitly mentioned.\n\n- Company name, set to \'Unknown\' if missingInput Snippet:\n"Stark Industries: Cybersecurity Analyst (mid-level). Three to five years in a SOC environment or equivalent. Familiarity with SIEM tools, incident response runbooks, and basic threat modelling."\n\nOutput valid JSON with no markdown code.\n\n', 'text': '{"company": "Stark Industries", "role": "Cybersecurity Analyst", "years_experience_required": 3, "notes": "Experience is specified as a range of three to five years."}', 'cost_usd': 8.189999999999998e-05, 'retries': 0, 'confidence': 0.95, 'sources': [], 'prompt_tokens': 286, 'completion_tokens': 65, 'snippet_id': 'j09', 'strategy': 'structured', 'latency': 1.3902650419986458, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_EmWUS3fltdmytIIzyRHOGKot', function=Function(arguments='{"content":"{\\"company\\": \\"Initech\\", \\"role\\": \\"Lead DevOps Engineer\\", \\"years_experience_required\\": 6, \\"notes\\": \\"Years of experience explicitly mentioned as \'around 6 years\'\\"}","confidence":1,"sources":[],"prompt_tokens":191,"completion_tokens":64}', name='answer_question'), type='function')]))
structured args: {'content': '{"company": "Initech", "role": "Lead DevOps Engineer", "years_experience_required": 6, "notes": "Years of experience explicitly mentioned as \'around 6 years\'"}', 'confidence': 1, 'sources': [], 'prompt_tokens': 191, 'completion_tokens': 64}
confidence (from the MODEL): 1
Response: {'question': 'You are an expert data extraction assistant. Extract job requirements from the text into a JSON object strictly matching this structural specification:\n\nEXPECTED JSON SCHEMA:\n{\n  "company": string,                   // Canonical company name, or "Unknown"\n  "role": string,                      // Specific job title\n  "years_experience_required": int|null, // Integer >= 0, or null if unspecified/ambiguous\n  "notes": string                      // Explicit justification for nulls or extracted ranges\n}\n\nFIELD RULES:\n- For years of experience extract one integer lowest from the range\n- If experience is not specified set years_experience_required to null.\n- Do not guess company names if not explicitly mentioned.\n\n- Company name, set to \'Unknown\' if missingInput Snippet:\n"Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD."\n\nOutput valid JSON with no markdown code.\n\n', 'text': '{"company": "Initech", "role": "Lead DevOps Engineer", "years_experience_required": 6, "notes": "Years of experience explicitly mentioned as \'around 6 years\'"}', 'cost_usd': 8.175e-05, 'retries': 0, 'confidence': 1.0, 'sources': [], 'prompt_tokens': 289, 'completion_tokens': 64, 'snippet_id': 'j04', 'strategy': 'structured', 'latency': 1.4189547950009, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_JWKc48VeXs3BgL2s2RzTwptx', function=Function(arguments='{"content":"{\\"company\\":\\"Hooli\\",\\"role\\":\\"Junior Frontend Developer\\",\\"years_experience_required\\":0,\\"notes\\":\\"Fresh grads welcome — no prior experience required.\\"}","confidence":0.95,"sources":[],"prompt_tokens":0,"completion_tokens":0}', name='answer_question'), type='function')]))
structured args: {'content': '{"company":"Hooli","role":"Junior Frontend Developer","years_experience_required":0,"notes":"Fresh grads welcome — no prior experience required."}', 'confidence': 0.95, 'sources': [], 'prompt_tokens': 0, 'completion_tokens': 0}
confidence (from the MODEL): 0.95
Response: {'question': 'You are an expert data extraction assistant. Extract job requirements from the text into a JSON object strictly matching this structural specification:\n\nEXPECTED JSON SCHEMA:\n{\n  "company": string,                   // Canonical company name, or "Unknown"\n  "role": string,                      // Specific job title\n  "years_experience_required": int|null, // Integer >= 0, or null if unspecified/ambiguous\n  "notes": string                      // Explicit justification for nulls or extracted ranges\n}\n\nFIELD RULES:\n- For years of experience extract one integer lowest from the range\n- If experience is not specified set years_experience_required to null.\n- Do not guess company names if not explicitly mentioned.\n\n- Company name, set to \'Unknown\' if missingInput Snippet:\n"Hooli is looking for a Junior Frontend Developer. Fresh grads welcome — no prior experience required. We care about curiosity and willingness to learn. JavaScript, React, and CSS fundamentals expected."\n\nOutput valid JSON with no markdown code.\n\n', 'text': '{"company":"Hooli","role":"Junior Frontend Developer","years_experience_required":0,"notes":"Fresh grads welcome — no prior experience required."}', 'cost_usd': 7.575e-05, 'retries': 0, 'confidence': 0.95, 'sources': [], 'prompt_tokens': 285, 'completion_tokens': 55, 'snippet_id': 'j05', 'strategy': 'structured', 'latency': 1.4252092339993396, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_jR2rcof1SENVV1OytHmyoMBh', function=Function(arguments='{"content":"{\\"company\\": \\"Pied Piper Inc.\\", \\"role\\": \\"Senior ML Engineer\\", \\"years_experience_required\\": 7, \\"notes\\": \\"Exceptional candidates with less experience are welcome.\\"}","confidence":0.9,"sources":[],"prompt_tokens":65,"completion_tokens":200}', name='answer_question'), type='function')]))
structured args: {'content': '{"company": "Pied Piper Inc.", "role": "Senior ML Engineer", "years_experience_required": 7, "notes": "Exceptional candidates with less experience are welcome."}', 'confidence': 0.9, 'sources': [], 'prompt_tokens': 65, 'completion_tokens': 200}
confidence (from the MODEL): 0.9
Response: {'question': 'Extract job details from the following job snippet with these keys:\n1.company, 2.role, 3.years_experience_required as integer, 4.notesExample 1:\nInput: "Globex International seeks a Senior Engineer with 5+ years of experience, joining timeframe immediate"\nOutput: {"company": "Globex International", "role": "Senior Engineer", "years_experience_required": 5, "notes": "Software Engineer, Immediate joining."}\n\nExample 2:\nInput: "We want a tester, ~3 years in software testing, for our stealth startup."\nOutput: {"company": "Unknown", "role": "Software Tester", "years_experience_required": 3, "notes": "Software Tester for sleath startup."}\n\nExample 3\nInput: "Looking for person for Sales Manager role on fastest growing company. The role will be inone of the Reliance Group of compaies."\nOutput: {"company": "Reliance Group", "role": "Sales Manager", "years_experience_required": null, "notes": "Looking for Sales maanger position, since manager position might require 10+ years experience."}\n\nInput snippet:\n"Pied Piper Inc. has an opening for a Senior ML Engineer. Compression algorithms background a plus. We typically look for 7+ years in production ML and distributed systems, but exceptional candidates with less are welcome."\n\nOutput valid JSON with no markdown code.\n\n', 'text': '{"company": "Pied Piper Inc.", "role": "Senior ML Engineer", "years_experience_required": 7, "notes": "Exceptional candidates with less experience are welcome."}', 'cost_usd': 9.375e-05, 'retries': 0, 'confidence': 0.9, 'sources': [], 'prompt_tokens': 373, 'completion_tokens': 63, 'snippet_id': 'j06', 'strategy': 'few_shot', 'latency': 1.4320047820001491, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_6yhUPCiMIPcQeIWIP8jKvXIl', function=Function(arguments='{"content":"{\\"company\\": \\"Northwind Ltd\\", \\"role\\": \\"Data Analyst\\", \\"years_experience_required\\": 2, \\"notes\\": \\"Data Analyst position reporting to Head of Analytics, working with SQL and dashboards.\\"}","confidence":1,"sources":[],"prompt_tokens":90,"completion_tokens":68}', name='answer_question'), type='function')]))
structured args: {'content': '{"company": "Northwind Ltd", "role": "Data Analyst", "years_experience_required": 2, "notes": "Data Analyst position reporting to Head of Analytics, working with SQL and dashboards."}', 'confidence': 1, 'sources': [], 'prompt_tokens': 90, 'completion_tokens': 68}
confidence (from the MODEL): 1
Response: {'question': 'Extract job details from the following job snippet with these keys:\n1.company, 2.role, 3.years_experience_required as integer, 4.notesExample 1:\nInput: "Globex International seeks a Senior Engineer with 5+ years of experience, joining timeframe immediate"\nOutput: {"company": "Globex International", "role": "Senior Engineer", "years_experience_required": 5, "notes": "Software Engineer, Immediate joining."}\n\nExample 2:\nInput: "We want a tester, ~3 years in software testing, for our stealth startup."\nOutput: {"company": "Unknown", "role": "Software Tester", "years_experience_required": 3, "notes": "Software Tester for sleath startup."}\n\nExample 3\nInput: "Looking for person for Sales Manager role on fastest growing company. The role will be inone of the Reliance Group of compaies."\nOutput: {"company": "Reliance Group", "role": "Sales Manager", "years_experience_required": null, "notes": "Looking for Sales maanger position, since manager position might require 10+ years experience."}\n\nInput snippet:\n"We\'re looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you\'ll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred."\n\nOutput valid JSON with no markdown code.\n\n', 'text': '{"company": "Northwind Ltd", "role": "Data Analyst", "years_experience_required": 2, "notes": "Data Analyst position reporting to Head of Analytics, working with SQL and dashboards."}', 'cost_usd': 9.404999999999998e-05, 'retries': 0, 'confidence': 1.0, 'sources': [], 'prompt_tokens': 367, 'completion_tokens': 65, 'snippet_id': 'j02', 'strategy': 'few_shot', 'latency': 1.457990241000516, 'parse_status': 1}


Raw structure: Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content=None, refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=[ChatCompletionMessageFunctionToolCall(id='call_568tsI7ZLGkb1DSZzcMkNmLB', function=Function(arguments='{"content":"{\\"company\\": \\"Wonka Confectionery Ltd.\\", \\"role\\": \\"Senior UX Researcher\\", \\"years_experience_required\\": 5, \\"notes\\": \\"Experience is specifically stated as five years of UX research experience.\\"}","confidence":0.95,"sources":[],"prompt_tokens":97,"completion_tokens":197}', name='answer_question'), type='function')]))

{'question': 'Extract job details from the following job snippet with these keys:\n1.company, 2.role, 3.years_experience_required as integer, 4.notesOutput valid JSON with no markdown code.\n\nInput Snippet: "Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems."',
 'text': '{"company": "Acme Corp", "role": "Senior Software Engineer", "years_experience_required": 5, "notes": "The ideal candidate has strong skills in Python and distributed systems."}',
 'cost_usd': 6.33e-05,
 'retries': 0,
 'confidence': 0.95,
 'sources': [],
 'prompt_tokens': 162,
 'completion_tokens': 65,
 'snippet_id': 'j01',
 'strategy': 'zero_shot',
 'latency': 2.376591009000549,
 'parse_status': 1}

In [10]:
for res in results:
    print(f"Data as {res['snippet_id']} | {res['strategy']} | {json.loads(res['text'])['company']} \n")

for gold in golden.values():
    print(f"Golden set as : {gold} \n")

for snipp in snippets.values():
    print(f"Snippets as : {snipp} \n")

Data as j01 | zero_shot | Acme Corp

Data as j01 | few_shot | Acme Corp

Data as j01 | structured | Acme Corp

Data as j01 | cot | Acme Corp

Data as j02 | zero_shot | Northwind Ltd.

Data as j02 | few_shot | Northwind Ltd

Data as j02 | structured | Northwind Ltd.

Data as j02 | cot | Northwind Ltd.

Data as j03 | zero_shot | Globex International

Data as j03 | few_shot | Globex International

Data as j03 | structured | Globex International

Data as j03 | cot | Globex International

Data as j04 | zero_shot | Initech

Data as j04 | few_shot | Initech

Data as j04 | structured | Initech

Data as j04 | cot | Initech

Data as j05 | zero_shot | Hooli

Data as j05 | few_shot | Hooli

Data as j05 | structured | Hooli

Data as j05 | cot | Hooli

Data as j06 | zero_shot | Pied Piper Inc.

Data as j06 | few_shot | Pied Piper Inc.

Data as j06 | structured | Pied Piper Inc.

Data as j06 | cot | Pied Piper Inc.

Data as j07 | zero_shot | Soylent Industries

Data as j07 | few_shot | Soylent Industries

Data as j07 | structured | Soylent Industries

Data as j07 | cot | Soylent Industries

Data as j08 | zero_shot | Wonka Confectionery Ltd.

Data as j08 | few_shot | Wonka Confectionery Ltd.

Data as j08 | structured | Wonka Confectionery Ltd.

Data as j08 | cot | Wonka Confectionery Ltd.

Data as j09 | zero_shot | Stark Industries

Data as j09 | few_shot | Stark Industries

Data as j09 | structured | Stark Industries

Data as j09 | cot | Stark Industries

Data as j10 | zero_shot | Cyberdyne Systems

Data as j10 | few_shot | Cyberdyne Systems

Data as j10 | structured | Cyberdyne Systems

Data as j10 | cot | Cyberdyne Systems

Golden set as : {'id': 'j01', 'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'clean — clear company + role + years'}

Golden set as : {'id': 'j02', 'company': 'Northwind Ltd', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': 'clean — preferred used but still a stated minimum'}

Golden set as : {'id': 'j03', 'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': "clean — 'at least 4 years'"}

Golden set as : {'id': 'j04', 'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': "slightly fuzzy — 'around 6 years' — accept 6"}

Golden set as : {'id': 'j05', 'company': 'Hooli', 'role': 'Junior Frontend Developer', 'years_experience_required': 0, 'notes': 'edge — fresh grads OK = 0 years'}

Golden set as : {'id': 'j06', 'company': 'Pied Piper Inc.', 'role': 'Senior ML Engineer', 'years_experience_required': 7, 'notes': "fuzzy — '7+ years' typically taken as 7; exceptional candidates clause is colour text"}

Golden set as : {'id': 'j07', 'company': 'Soylent Industries', 'role': 'Engineering Manager', 'years_experience_required': 3, 'notes': "spelled-out number — 'about three years' → 3"}

Golden set as : {'id': 'j08', 'company': 'Wonka Confectionery Ltd', 'role': 'Senior UX Researcher', 'years_experience_required': 5, 'notes': "clean — 'five years' → 5"}

Golden set as : {'id': 'j09', 'company': 'Stark Industries', 'role': 'Cybersecurity Analyst', 'years_experience_required': 3, 'notes': "range 3-5 — take the minimum, 3. Accept 3 or 'between 3 and 5'."}

Golden set as : {'id': 'j10', 'company': 'Cyberdyne Systems', 'role': 'AI/ML Research Scientist', 'years_experience_required': None, 'notes': 'edge — no years stated. Correct answer: null. Penalise if model fabricates a number.'}

Snippets as : {'id': 'j01', 'snippet': 'Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.'}

Snippets as : {'id': 'j02', 'snippet': "We're looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred."}

Snippets as : {'id': 'j03', 'snippet': "Globex International seeks a Product Manager - Growth. You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts."}

Snippets as : {'id': 'j04', 'snippet': 'Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.'}

Snippets as : {'id': 'j05', 'snippet': 'Hooli is looking for a Junior Frontend Developer. Fresh grads welcome — no prior experience required. We care about curiosity and willingness to learn. JavaScript, React, and CSS fundamentals expected.'}

Snippets as : {'id': 'j06', 'snippet': 'Pied Piper Inc. has an opening for a Senior ML Engineer. Compression algorithms background a plus. We typically look for 7+ years in production ML and distributed systems, but exceptional candidates with less are welcome.'}

Snippets as : {'id': 'j07', 'snippet': "We want a builder. Soylent Industries is growing fast. The role is Engineering Manager. About three years leading engineering teams, plus a solid IC background before that. Apply if you've shipped real products."}

Snippets as : {'id': 'j08', 'snippet': "Senior UX Researcher at Wonka Confectionery Ltd. You'll design and run user studies for our digital storefront. Five years of UX research experience or equivalent portfolio required."}

Snippets as : {'id': 'j09', 'snippet': 'Stark Industries: Cybersecurity Analyst (mid-level). Three to five years in a SOC environment or equivalent. Familiarity with SIEM tools, incident response runbooks, and basic threat modelling.'}

Snippets as : {'id': 'j10', 'snippet': "Cyberdyne Systems is hiring. Role: AI/ML Research Scientist. PhD preferred but not required. Strong publication record in deep learning or reinforcement learning. We don't list a specific years requirement — we hire on demonstrated impact."}

## Step 4 — Score against the golden set

Three scores per (strategy × snippet) pair:

1. **accuracy** — how many of 3 fields match (0, 1, 2, or 3)?
2. **parse_success** — did the response parse cleanly?
3. **llm_judge_score** — 1-4 score from gpt-4o-as-judge

**TODO:** implement the three score functions.

In [11]:
RUBRIC = """You are a strict, fair evaluator of responses from a job snippet extraction assistant.
Score the CANDIDATE answer against the IDEAL response set on three dimensions, each 1-4:

- accuracy    : are the facts correct and complete versus the ideal? (1 Poor .. 4 Excellent)
- groundedness: is it supported by the ideal/source, with nothing invented or contradictory?
- format      : is it clear, appropriately concise, and well-structured?

Three fields: Company name, years_experience_required, role. Notes to have valid reasoning.

Scale: 1 = Poor (none correct or unparsable), 2 = OK (one of three correct, or fabricated a field), 
3 = Good (two of three correct, no fabricated data), 4 = Excellent (all three fields correct).
Be strict on accuracy: an answer that omits a key fact or contradicts the ideal cannot score above 2.
Return your scores and a one-paragraph reasoning that names specific facts."""

JUDGE_TOOL = {
    "type": "function",
    "function": {
        "name": "submit_scores",
        "description": "Submit rubric scores and reasoning for the candidate answer.",
        "parameters": {
            "type": "object",
            "properties": {
                "accuracy":     {"type": "integer", "minimum": 1, "maximum": 4},
                "groundedness": {"type": "integer", "minimum": 1, "maximum": 4},
                "format":       {"type": "integer", "minimum": 1, "maximum": 4},
                "reasoning":    {"type": "string"},
            },
            "required": ["accuracy", "groundedness", "format", "reasoning"],
        },
    },
}


def build_messages(snippet, extracted, gold):
    user = (f"JOB SNIPPET:\n{snippet}\n\n"
            f"EXTRACTED RESULT:\n{extracted}\n\n"
            f"IDEAL RESULT:\n{gold}")
    return [{"role": "system", "content": RUBRIC},
            {"role": "user",   "content": user}]

#print(build_messages(gold???, golden[0]["ideal_answer"], candidates["good"])[1]["content"])

In [12]:

def score_accuracy(extracted: dict | None, gold: dict) -> int:
    """Compare 3 fields. Case-insensitive, whitespace-trimmed for strings. Return 0, 1, 2, or 3."""
    # TODO: count exact matches (with normalisation)
    raise NotImplementedError


async def score_llm_judge(snippet_text: str, extracted: dict | None, gold: dict) -> int:
    """Use gpt-4o as a judge. Return integer 1-4.
    
    Rubric (suggested):
      4 — all three fields correct
      3 — two of three correct, no fabricated data
      2 — one of three correct, or fabricated a field
      1 — none correct or unparsable
    """
    # TODO: prompt the judge with both the gold and the extracted, ask for a 1-4 score
    from openai import OpenAI
    client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])
    resp = client.chat.completions.create(
        model=JUDGE_MODEL, #"gpt-4o-mini",
        temperature=0,                       # judging should be as consistent as possible
        messages=build_messages(snippet_text, extracted, gold),
        tools=[JUDGE_TOOL],
        tool_choice={"type": "function", "function": {"name": "submit_scores"}},
      )
    return json.loads(resp.choices[0].message.tool_calls[0].function.arguments)

In [13]:
for res in results:
    print(f"Data as {res['snippet_id']} | {res['strategy']} | {json.loads(res['text'])} \n")

Data as j01 | zero_shot | {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'The ideal candidate has strong skills in Python and distributed systems.'}

Data as j01 | few_shot | {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'Hiring for a Senior Software Engineer position in the platform team with backend development experience in Python and distributed systems.'}

Data as j01 | structured | {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': '5+ years specified, lowest integer extracted.'}

Data as j01 | cot | {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.'}

Data as j02 | zero_shot | {'company': 'Northwind Ltd.', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': "Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred."}

Data as j02 | few_shot | {'company': 'Northwind Ltd', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': 'Data Analyst position reporting to Head of Analytics, working with SQL and dashboards.'}

Data as j02 | structured | {'company': 'Northwind Ltd.', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': '2 years minimum experience preferred.'}

Data as j02 | cot | {'company': 'Northwind Ltd.', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': '2 years minimum experience preferred.'}

Data as j03 | zero_shot | {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': "You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts."}

Data as j03 | few_shot | {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': 'At least 4 years of product management experience in B2C contexts.'}

Data as j03 | structured | {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': 'Experience required is explicitly stated as at least 4 years.'}

Data as j03 | cot | {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': 'The role involves owning activation and onboarding metrics across consumer apps, requiring product management experience in B2C contexts.'}

Data as j04 | zero_shot | {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': 'We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.'}

Data as j04 | few_shot | {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': 'Builder role expected with hands-on infrastructure work in AWS, Terraform, and modern CI/CD.'}

Data as j04 | structured | {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': "Years of experience explicitly mentioned as 'around 6 years'"}

Data as j04 | cot | {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': 'Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.'}

Data as j05 | zero_shot | {'company': 'Hooli', 'role': 'Junior Frontend Developer', 'years_experience_required': 0, 'notes': 'Fresh grads welcome — no prior experience required. We care about curiosity and willingness to learn. JavaScript, React, and CSS fundamentals expected.'}

Data as j05 | few_shot | {'company': 'Hooli', 'role': 'Junior Frontend Developer', 'years_experience_required': 0, 'notes': 'Fresh grads welcome, no prior experience required. Expecting knowledge in JavaScript, React, and CSS fundamentals.'}

Data as j05 | structured | {'company': 'Hooli', 'role': 'Junior Frontend Developer', 'years_experience_required': 0, 'notes': 'Fresh grads welcome — no prior experience required.'}

Data as j05 | cot | {'company': 'Hooli', 'role': 'Junior Frontend Developer', 'years_experience_required': None, 'notes': 'Fresh grads welcome — no prior experience required. We care about curiosity and willingness to learn. JavaScript, React, and CSS fundamentals expected.'}

Data as j06 | zero_shot | {'company': 'Pied Piper Inc.', 'role': 'Senior ML Engineer', 'years_experience_required': 7, 'notes': 'Compression algorithms background a plus. We typically look for 7+ years in production ML and distributed systems, but exceptional candidates with less are welcome.'}

Data as j06 | few_shot | {'company': 'Pied Piper Inc.', 'role': 'Senior ML Engineer', 'years_experience_required': 7, 'notes': 'Exceptional candidates with less experience are welcome.'}

Data as j06 | structured | {'company': 'Pied Piper Inc.', 'role': 'Senior ML Engineer', 'years_experience_required': 7, 'notes': 'The requirement is 7+ years, thus the lowest integer is 7. Exceptional candidates with less experience are welcome, but that does not specify an explicit lower range.'}

Data as j06 | cot | {'company': 'Pied Piper Inc.', 'role': 'Senior ML Engineer', 'years_experience_required': 7, 'notes': 'Compression algorithms background a plus; We typically look for 7+ years in production ML and distributed systems, but exceptional candidates with less are welcome.'}

Data as j07 | zero_shot | {'company': 'Soylent Industries', 'role': 'Engineering Manager', 'years_experience_required': 3, 'notes': "About three years leading engineering teams, plus a solid IC background before that. Apply if you've shipped real products."}

Data as j07 | few_shot | {'company': 'Soylent Industries', 'role': 'Engineering Manager', 'years_experience_required': 3, 'notes': 'Looking for a builder to lead engineering teams with a solid IC background and experience shipping real products.'}

Data as j07 | structured | {'company': 'Soylent Industries', 'role': 'Engineering Manager', 'years_experience_required': 3, 'notes': "Experience specified as 'About three years leading engineering teams'."}

Data as j07 | cot | {'company': 'Soylent Industries', 'role': 'Engineering Manager', 'years_experience_required': 3, 'notes': 'About three years leading engineering teams, plus a solid IC background before that. Applying indicates familiarity with shipping real products.'}

Data as j08 | zero_shot | {'company': 'Wonka Confectionery Ltd.', 'role': 'Senior UX Researcher', 'years_experience_required': 5, 'notes': "You'll design and run user studies for our digital storefront. Five years of UX research experience or equivalent portfolio required."}

Data as j08 | few_shot | {'company': 'Wonka Confectionery Ltd.', 'role': 'Senior UX Researcher', 'years_experience_required': 5, 'notes': 'Design and run user studies for the digital storefront.'}

Data as j08 | structured | {'company': 'Wonka Confectionery Ltd.', 'role': 'Senior UX Researcher', 'years_experience_required': 5, 'notes': 'Experience is specifically stated as five years of UX research experience.'}

Data as j08 | cot | {'company': 'Wonka Confectionery Ltd.', 'role': 'Senior UX Researcher', 'years_experience_required': 5, 'notes': "You'll design and run user studies for our digital storefront."}

Data as j09 | zero_shot | {'company': 'Stark Industries', 'role': 'Cybersecurity Analyst', 'years_experience_required': 4, 'notes': 'Three to five years in a SOC environment or equivalent. Familiarity with SIEM tools, incident response runbooks, and basic threat modelling.'}

Data as j09 | few_shot | {'company': 'Stark Industries', 'role': 'Cybersecurity Analyst', 'years_experience_required': 4, 'notes': 'Mid-level position requiring 3 to 5 years in a SOC environment or equivalent.'}

Data as j09 | structured | {'company': 'Stark Industries', 'role': 'Cybersecurity Analyst', 'years_experience_required': 3, 'notes': 'Experience is specified as a range of three to five years.'}

Data as j09 | cot | {'company': 'Stark Industries', 'role': 'Cybersecurity Analyst', 'years_experience_required': 4, 'notes': 'Three to five years in a SOC environment or equivalent.'}

Data as j10 | zero_shot | {'company': 'Cyberdyne Systems', 'role': 'AI/ML Research Scientist', 'years_experience_required': 0, 'notes': "PhD preferred but not required. Strong publication record in deep learning or reinforcement learning. We don't list a specific years requirement — we hire on demonstrated impact."}

Data as j10 | few_shot | {'company': 'Cyberdyne Systems', 'role': 'AI/ML Research Scientist', 'years_experience_required': None, 'notes': 'PhD preferred but not required. Strong publication record in deep learning or reinforcement learning. Hiring based on demonstrated impact.'}

Data as j10 | structured | {'company': 'Cyberdyne Systems', 'role': 'AI/ML Research Scientist', 'years_experience_required': None, 'notes': 'Experience requirement is not specified; we hire based on demonstrated impact.'}

Data as j10 | cot | {'company': 'Cyberdyne Systems', 'role': 'AI/ML Research Scientist', 'years_experience_required': None, 'notes': "PhD preferred but not required. Strong publication record in deep learning or reinforcement learning. We don't list a specific years requirement — we hire on demonstrated impact."}

In [14]:
# Apply scoring to all 40 results
# TODO: loop through results, attach accuracy + parse_success + llm_judge_score to each row
scored = []   # list of result dicts with scoring fields added

for result in results:
    txt = json.loads(result['text'])
    print(f"{snippets[result['snippet_id']]['snippet']}\n, {txt}, {result['strategy']}, \n {golden[result['snippet_id']]}\n\n")
    judge_result = await score_llm_judge(snippets[result['snippet_id']]['snippet'], txt, golden[result['snippet_id']] )
    judge_result['strategy'] = result['strategy']
    judge_result['snippet_id'] = result['snippet_id']
    judge_result['cost_usd'] = result['cost_usd']
    judge_result['latency'] = result['latency']
    judge_result['parse_status'] = result['parse_status']
    if judge_result['parse_status'] ==1:
        judge_result['llm_judge_score'] = judge_result['accuracy']*0.5+judge_result['groundedness']*0.3+judge_result['format']*0.15
    else:
        judge_result['llm_judge_score'] = 0

    print(f"Judge: {judge_result}")
    #print(f"Data as {res['snippet_id']} | {res['strategy']} | {json.loads(res['text'])['company']} \n")
    scored.append(judge_result)


print(f'Scored {len(scored)} results.')

Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.
, {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'The ideal candidate has strong skills in Python and distributed systems.'}, zero_shot,
 {'id': 'j01', 'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'clean — clear company + role + years'}

Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result is fully accurate and matches the ideal result in all key aspects. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and match the ideal. The notes field is also consistent with the ideal, providing additional context about the skills required. The format is clear, concise, and well-structured, making it easy to read and understand. There are no inaccuracies or unsupported claims, thus earning a perfect score in all dimensions.", 'strategy': 'zero_shot', 'snippet_id': 'j01', 'cost_usd': 6.33e-05, 'latency': 2.376591009000549, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.
, {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'Hiring for a Senior Software Engineer position in the platform team with backend development experience in Python and distributed systems.'}, few_shot,
 {'id': 'j01', 'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'clean — clear company + role + years'}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result is fully accurate and matches the ideal response. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and aligned with the job snippet. The notes provide a concise summary of the job requirements, specifically mentioning the platform team, backend development, Python, and distributed systems, which are all supported by the source text. The format is clear, concise, and well-structured, making it easy to understand. Therefore, the candidate's response scores a 4 in all dimensions.", 'strategy': 'few_shot', 'snippet_id': 'j01', 'cost_usd': 9.944999999999999e-05, 'latency': 1.637516961000074, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.
, {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': '5+ years specified, lowest integer extracted.'}, structured,
 {'id': 'j01', 'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'clean — clear company + role + years'}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and extracted. The note about extracting the lowest integer from '5+' is accurate and aligns with the ideal result's note. The format is clear, concise, and well-structured, making it easy to compare with the ideal result. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.", 'strategy': 'structured', 'snippet_id': 'j01', 'cost_usd': 7.845e-05, 'latency': 1.5434256779990392, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Acme Corp is hiring a Senior Software Engineer to join our platform team. The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.
, {'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'The ideal candidate has 5+ years of backend development experience and strong skills in Python and distributed systems.'}, cot,
 {'id': 'j01', 'company': 'Acme Corp', 'role': 'Senior Software Engineer', 'years_experience_required': 5, 'notes': 'clean — clear company + role + years'}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, providing a clear summary of the job requirements. The format is clear and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.", 'strategy': 'cot', 'snippet_id': 'j01', 'cost_usd': 7.664999999999999e-05, 'latency': 1.5518434650002746, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
We're looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred.
, {'company': 'Northwind Ltd.', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': "Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred."}, zero_shot,
 {'id': 'j02', 'company': 'Northwind Ltd', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': 'clean — preferred used but still a stated minimum'}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result in all key fields: company name ('Northwind Ltd.'), role ('Data Analyst'), and years of experience required (2). The notes field in the candidate's response is more detailed but does not contradict the ideal result, which is acceptable. The format is clear and well-structured, with all necessary information included and no extraneous or fabricated data. Therefore, the candidate's response scores 4 in accuracy, groundedness, and format.", 'strategy': 'zero_shot', 'snippet_id': 'j02', 'cost_usd': 7.11e-05, 'latency': 1.6320054280004115, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
We're looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred.
, {'company': 'Northwind Ltd', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': 'Data Analyst position reporting to Head of Analytics, working with SQL and dashboards.'}, few_shot,
 {'id': 'j02', 'company': 'Northwind Ltd', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': 'clean — preferred used but still a stated minimum'}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Northwind Ltd', the role 'Data Analyst', and the years of experience required '2' are all correctly identified and match the ideal response. The notes field is also accurate, capturing the essence of the job description without adding any ungrounded information. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.", 'strategy': 'few_shot', 'snippet_id': 'j02', 'cost_usd': 9.404999999999998e-05, 'latency': 1.457990241000516, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
We're looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred.
, {'company': 'Northwind Ltd.', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': '2 years minimum experience preferred.'}, structured,
 {'id': 'j02', 'company': 'Northwind Ltd', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': 'clean — preferred used but still a stated minimum'}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Northwind Ltd.', the role 'Data Analyst', and the years of experience required '2' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, accurately reflecting the job snippet's language about experience preference. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the scores for accuracy, groundedness, and format are all 4.", 'strategy': 'structured', 'snippet_id': 'j02', 'cost_usd': 7.664999999999999e-05, 'latency': 1.9794638090024819, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
We're looking for a Data Analyst at Northwind Ltd. Reporting to the Head of Analytics, you'll work with SQL, dashboards, and stakeholder requests. 2 years minimum experience preferred.
, {'company': 'Northwind Ltd.', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': '2 years minimum experience preferred.'}, cot,
 {'id': 'j02', 'company': 'Northwind Ltd', 'role': 'Data Analyst', 'years_experience_required': 2, 'notes': 'clean — preferred used but still a stated minimum'}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Northwind Ltd.', the role 'Data Analyst', and the years of experience required '2' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, accurately reflecting the job snippet's language about experience preference. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.", 'strategy': 'cot', 'snippet_id': 'j02', 'cost_usd': 6.764999999999999e-05, 'latency': 1.3859710979995725, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Globex International seeks a Product Manager - Growth. You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts.
, {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': "You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts."}, zero_shot,
 {'id': 'j03', 'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': "clean — 'at least 4 years'"}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, capturing the essence of the job requirements without introducing any inaccuracies or fabrications. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.", 'strategy': 'zero_shot', 'snippet_id': 'j03', 'cost_usd': 7.185e-05, 'latency': 2.4274953280000773, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Globex International seeks a Product Manager - Growth. You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts.
, {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': 'At least 4 years of product management experience in B2C contexts.'}, few_shot,
 {'id': 'j03', 'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': "clean — 'at least 4 years'"}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes also accurately reflect the requirement of 'at least 4 years of product management experience in B2C contexts', which aligns with the ideal result's note. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.", 'strategy': 'few_shot', 'snippet_id': 'j03', 'cost_usd': 9.6e-05, 'latency': 1.6242738170003577, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Globex International seeks a Product Manager - Growth. You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts.
, {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': 'Experience required is explicitly stated as at least 4 years.'}, structured,
 {'id': 'j03', 'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': "clean — 'at least 4 years'"}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes also accurately reflect the requirement of 'at least 4 years' of experience, which is consistent with the job snippet. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.", 'strategy': 'structured', 'snippet_id': 'j03', 'cost_usd': 7.86e-05, 'latency': 1.3930429220017686, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Globex International seeks a Product Manager - Growth. You'll own activation and onboarding metrics across our consumer apps. We're looking for someone with at least 4 years of product management experience in B2C contexts.
, {'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': 'The role involves owning activation and onboarding metrics across consumer apps, requiring product management experience in B2C contexts.'}, cot,
 {'id': 'j03', 'company': 'Globex International', 'role': 'Product Manager - Growth', 'years_experience_required': 4, 'notes': "clean — 'at least 4 years'"}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes section in the candidate's response provides additional context about the role, which is consistent with the job snippet and does not contradict the ideal result. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.", 'strategy': 'cot', 'snippet_id': 'j03', 'cost_usd': 7.860000000000001e-05, 'latency': 2.1443358049982635, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.
, {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': 'We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.'}, zero_shot,
 {'id': 'j04', 'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': "slightly fuzzy — 'around 6 years' — accept 6"}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly in all fields. The company name 'Initech', the role 'Lead DevOps Engineer', and the years of experience required '6' are all correctly identified and match the ideal response. The notes field is also accurately captured, reflecting the job's emphasis on building rather than maintaining, and the specific technologies mentioned. There are no inaccuracies or unsupported claims, and the format is clear and well-structured.", 'strategy': 'zero_shot', 'snippet_id': 'j04', 'cost_usd': 7.62e-05, 'latency': 1.5968238129971724, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.
, {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': 'Builder role expected with hands-on infrastructure work in AWS, Terraform, and modern CI/CD.'}, few_shot,
 {'id': 'j04', 'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': "slightly fuzzy — 'around 6 years' — accept 6"}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Initech', the role 'Lead DevOps Engineer', and the years of experience required '6' are all correctly identified and match the ideal response. The notes also accurately reflect the job snippet's emphasis on a builder role with specific technologies, aligning with the ideal's note on the slightly fuzzy experience requirement. The format is clear, concise, and well-structured, making it an excellent response across all dimensions.", 'strategy': 'few_shot', 'snippet_id': 'j04', 'cost_usd': 9.855e-05, 'latency': 1.49114734700197, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.
, {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': "Years of experience explicitly mentioned as 'around 6 years'"}, structured,
 {'id': 'j04', 'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': "slightly fuzzy — 'around 6 years' — accept 6"}


Judge: {'accuracy': 4, 'groundedness': 4, 'format': 4, 'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Initech', the role 'Lead DevOps Engineer', and the years of experience required '6' are all correctly identified and match the ideal response. The notes also accurately reflect the slightly fuzzy nature of the experience requirement, using the phrase 'around 6 years' as mentioned in the job snippet. There are no inaccuracies, unsupported claims, or formatting issues present in the candidate's response.", 'strategy': 'structured', 'snippet_id': 'j04', 'cost_usd': 8.175e-05, 'latency': 1.4189547950009, 'parse_status': 1, 'llm_judge_score': 3.8000000000000003}
Join Initech as a Lead DevOps Engineer. We need a builder, not a maintainer. Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.
, {'company': 'Initech', 'role': 'Lead DevOps Engineer', 'years_experience_required': 6, 'notes': 'Around 6 years of hands-on infrastructure work expected, ideally with AWS, Terraform, and modern CI/CD.'}, cot,

In [15]:
scored

[{'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result is fully accurate and matches the ideal result in all key aspects. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and match the ideal. The notes field is also consistent with the ideal, providing additional context about the skills required. The format is clear, concise, and well-structured, making it easy to read and understand. There are no inaccuracies or unsupported claims, thus earning a perfect score in all dimensions.",
  'strategy': 'zero_shot',
  'snippet_id': 'j01',
  'cost_usd': 6.33e-05,
  'latency': 2.376591009000549,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result is fully accurate and matches the ideal response. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and aligned with the job snippet. The notes provide a concise summary of the job requirements, specifically mentioning the platform team, backend development, Python, and distributed systems, which are all supported by the source text. The format is clear, concise, and well-structured, making it easy to understand. Therefore, the candidate's response scores a 4 in all dimensions.",
  'strategy': 'few_shot',
  'snippet_id': 'j01',
  'cost_usd': 9.944999999999999e-05,
  'latency': 1.637516961000074,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and extracted. The note about extracting the lowest integer from '5+' is accurate and aligns with the ideal result's note. The format is clear, concise, and well-structured, making it easy to compare with the ideal result. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.",
  'strategy': 'structured',
  'snippet_id': 'j01',
  'cost_usd': 7.845e-05,
  'latency': 1.5434256779990392,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Acme Corp', the role 'Senior Software Engineer', and the years of experience required '5' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, providing a clear summary of the job requirements. The format is clear and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.",
  'strategy': 'cot',
  'snippet_id': 'j01',
  'cost_usd': 7.664999999999999e-05,
  'latency': 1.5518434650002746,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result in all key fields: company name ('Northwind Ltd.'), role ('Data Analyst'), and years of experience required (2). The notes field in the candidate's response is more detailed but does not contradict the ideal result, which is acceptable. The format is clear and well-structured, with all necessary information included and no extraneous or fabricated data. Therefore, the candidate's response scores 4 in accuracy, groundedness, and format.",
  'strategy': 'zero_shot',
  'snippet_id': 'j02',
  'cost_usd': 7.11e-05,
  'latency': 1.6320054280004115,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Northwind Ltd', the role 'Data Analyst', and the years of experience required '2' are all correctly identified and match the ideal response. The notes field is also accurate, capturing the essence of the job description without adding any ungrounded information. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.",
  'strategy': 'few_shot',
  'snippet_id': 'j02',
  'cost_usd': 9.404999999999998e-05,
  'latency': 1.457990241000516,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Northwind Ltd.', the role 'Data Analyst', and the years of experience required '2' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, accurately reflecting the job snippet's language about experience preference. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the scores for accuracy, groundedness, and format are all 4.",
  'strategy': 'structured',
  'snippet_id': 'j02',
  'cost_usd': 7.664999999999999e-05,
  'latency': 1.9794638090024819,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Northwind Ltd.', the role 'Data Analyst', and the years of experience required '2' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, accurately reflecting the job snippet's language about experience preference. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.",
  'strategy': 'cot',
  'snippet_id': 'j02',
  'cost_usd': 6.764999999999999e-05,
  'latency': 1.3859710979995725,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes field is also consistent with the ideal, capturing the essence of the job requirements without introducing any inaccuracies or fabrications. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.",
  'strategy': 'zero_shot',
  'snippet_id': 'j03',
  'cost_usd': 7.185e-05,
  'latency': 2.4274953280000773,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes also accurately reflect the requirement of 'at least 4 years of product management experience in B2C contexts', which aligns with the ideal result's note. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.",
  'strategy': 'few_shot',
  'snippet_id': 'j03',
  'cost_usd': 9.6e-05,
  'latency': 1.6242738170003577,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes also accurately reflect the requirement of 'at least 4 years' of experience, which is consistent with the job snippet. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in all dimensions.",
  'strategy': 'structured',
  'snippet_id': 'j03',
  'cost_usd': 7.86e-05,
  'latency': 1.3930429220017686,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Globex International', the role 'Product Manager - Growth', and the years of experience required '4' are all correctly identified and match the ideal response. The notes section in the candidate's response provides additional context about the role, which is consistent with the job snippet and does not contradict the ideal result. The format is clear, concise, and well-structured, making it easy to read and understand. Therefore, the candidate's response scores a 4 in accuracy, groundedness, and format.",
  'strategy': 'cot',
  'snippet_id': 'j03',
  'cost_usd': 7.860000000000001e-05,
  'latency': 2.1443358049982635,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly in all fields. The company name 'Initech', the role 'Lead DevOps Engineer', and the years of experience required '6' are all correctly identified and match the ideal response. The notes field is also accurately captured, reflecting the job's emphasis on building rather than maintaining, and the specific technologies mentioned. There are no inaccuracies or unsupported claims, and the format is clear and well-structured.",
  'strategy': 'zero_shot',
  'snippet_id': 'j04',
  'cost_usd': 7.62e-05,
  'latency': 1.5968238129971724,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Initech', the role 'Lead DevOps Engineer', and the years of experience required '6' are all correctly identified and match the ideal response. The notes also accurately reflect the job snippet's emphasis on a builder role with specific technologies, aligning with the ideal's note on the slightly fuzzy experience requirement. The format is clear, concise, and well-structured, making it an excellent response across all dimensions.",
  'strategy': 'few_shot',
  'snippet_id': 'j04',
  'cost_usd': 9.855e-05,
  'latency': 1.49114734700197,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Initech', the role 'Lead DevOps Engineer', and the years of experience required '6' are all correctly identified and match the ideal response. The notes also accurately reflect the slightly fuzzy nature of the experience requirement, using the phrase 'around 6 years' as mentioned in the job snippet. There are no inaccuracies, unsupported claims, or formatting issues present in the candidate's response.",
  'strategy': 'structured',
  'snippet_id': 'j04',
  'cost_usd': 8.175e-05,
  'latency': 1.4189547950009,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly in terms of accuracy, groundedness, and format. The company name 'Initech', the role 'Lead DevOps Engineer', and the years of experience required '6' are all correctly extracted and align with the job snippet. The notes also accurately reflect the slightly fuzzy nature of the experience requirement, as indicated in the ideal result. The format is clear and concise, with all necessary information included and no extraneous details.",
  'strategy': 'cot',
  'snippet_id': 'j04',
  'cost_usd': 7.815e-05,
  'latency': 1.6164652990009927,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result is fully accurate and matches the ideal response. The company name 'Hooli', the role 'Junior Frontend Developer', and the 'years_experience_required' as 0 are all correctly identified. The notes are also consistent with the job snippet, emphasizing that fresh graduates are welcome and no prior experience is required. The format is clear, concise, and well-structured, making it an excellent response.",
  'strategy': 'zero_shot',
  'snippet_id': 'j05',
  'cost_usd': 7.335e-05,
  'latency': 1.9158737100005965,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result is fully accurate and matches the ideal response. The company name 'Hooli', the role 'Junior Frontend Developer', and the years of experience required '0' are all correctly identified. The notes section is also accurate, capturing the essence of the job snippet by mentioning that fresh graduates are welcome and no prior experience is required, along with the expected knowledge in JavaScript, React, and CSS fundamentals. The format is clear, concise, and well-structured, making it easy to understand.",
  'strategy': 'few_shot',
  'snippet_id': 'j05',
  'cost_usd': 0.00010035,
  'latency': 1.5585129150022112,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result is accurate and complete. The company name 'Hooli', the role 'Junior Frontend Developer', and the 'years_experience_required' as 0 are all correctly identified and match the ideal result. The notes also correctly reflect the job snippet's emphasis on welcoming fresh graduates with no prior experience required. The format is clear, concise, and well-structured, aligning perfectly with the ideal response.",
  'strategy': 'structured',
  'snippet_id': 'j05',
  'cost_usd': 7.575e-05,
  'latency': 1.4252092339993396,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 2,
  'groundedness': 2,
  'format': 3,
  'reasoning': "The candidate correctly identified the company as 'Hooli' and the role as 'Junior Frontend Developer', which matches the ideal response. However, the 'years_experience_required' field is incorrect. The candidate used 'None' instead of '0', which is a key detail indicating that no experience is required. This omission affects both accuracy and groundedness, as it contradicts the ideal response. The format is clear and well-structured, but due to the inaccuracy in the experience field, the overall score is limited.",
  'strategy': 'cot',
  'snippet_id': 'j05',
  'cost_usd': 8.13e-05,
  'latency': 1.73403525699905,
  'parse_status': 1,
  'llm_judge_score': 2.05},
 {'accuracy': 3,
  'groundedness': 3,
  'format': 4,
  'reasoning': "The candidate's answer correctly identifies the company as 'Pied Piper Inc.' and the role as 'Senior ML Engineer', matching the ideal response. However, the 'years_experience_required' field is slightly misrepresented. While the candidate states '7', the ideal response notes that '7+ years' is typically taken as 7, but also highlights the clause about exceptional candidates, which adds nuance. This omission affects accuracy and groundedness, as the candidate's response does not fully capture the flexibility mentioned in the job snippet. The format is clear and well-structured, aligning with the ideal response.",
  'strategy': 'zero_shot',
  'snippet_id': 'j06',
  'cost_usd': 7.575e-05,
  'latency': 1.6482494559968472,
  'parse_status': 1,
  'llm_judge_score': 3.0},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result is fully accurate and matches the ideal response. The company name 'Pied Piper Inc.' and the role 'Senior ML Engineer' are correctly identified. The years of experience required is correctly noted as 7, aligning with the '7+ years' mentioned in the job snippet. Additionally, the note about exceptional candidates with less experience is included, which is consistent with the ideal response's mention of this clause as color text. The format is clear, concise, and well-structured, making it an excellent response.",
  'strategy': 'few_shot',
  'snippet_id': 'j06',
  'cost_usd': 9.375e-05,
  'latency': 1.4320047820001491,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result in all key aspects. The company name 'Pied Piper Inc.', the role 'Senior ML Engineer', and the years of experience required '7' are all correctly identified and aligned with the ideal response. The notes also accurately reflect the nuance of the experience requirement, acknowledging the possibility for exceptional candidates with less experience, which is consistent with the ideal response. The format is clear, concise, and well-structured, making it easy to understand and compare with the ideal result.",
  'strategy': 'structured',
  'snippet_id': 'j06',
  'cost_usd': 9.554999999999999e-05,
  'latency': 1.576537783999811,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 3,
  'groundedness': 3,
  'format': 4,
  'reasoning': "The candidate's response correctly identifies the company as 'Pied Piper Inc.' and the role as 'Senior ML Engineer', which matches the ideal response. However, the 'years_experience_required' field is slightly misrepresented. The candidate states '7', while the ideal response notes that '7+ years' is typically taken as 7, but also mentions that exceptional candidates with less experience are welcome. This nuance is not fully captured in the candidate's response, affecting accuracy and groundedness. The format is clear and well-structured, matching the ideal response's structure.",
  'strategy': 'cot',
  'snippet_id': 'j06',
  'cost_usd': 8.37e-05,
  'latency': 1.6113122670030862,
  'parse_status': 1,
  'llm_judge_score': 3.0},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result matches the ideal result perfectly. The company name 'Soylent Industries', the role 'Engineering Manager', and the years of experience required '3' are all correctly identified and extracted. The notes field is also accurately captured, reflecting the requirement for about three years of experience leading engineering teams and a solid IC background. The format is clear, concise, and well-structured, with no extraneous information or errors.",
  'strategy': 'zero_shot',
  'snippet_id': 'j07',
  'cost_usd': 6.51e-05,
  'latency': 1.8318307100016682,
  'parse_status': 1,
  'llm_judge_score': 3.8000000000000003},
 {'accuracy': 4,
  'groundedness': 4,
  'format': 4,
  'reasoning': "The candidate's extracted result is fully accurate and matches the ideal response. The company name 'Soylent Industries', the role 'Engineering Manager', and the years of experience required '3' are all correctly identified and extracted. The notes section accurately captures the additional context about the role, including the need for a solid IC background and experience in shipping real products. The format is clear, concise, and well-structured, aligning perfectly with the ideal result.",
  'strategy': 'few_shot',
  'snippet_id': 'j07',
  'cost_usd': 9.81e-05,
  'latency': 1.5098399609996704,
  'parse_status': 1,

## Step 5 — Build the comparison table

In [16]:
df = pd.DataFrame(scored)

summary = df.groupby('strategy').agg({
    'accuracy': 'mean',
    'parse_status': 'mean',
    'llm_judge_score': 'mean',
    'cost_usd': 'sum',
    'latency': 'median',
}).round(3)

summary.columns = ['Accuracy based on judge of all 3 fields', 'Parse rate', 'Judge score', 'Total cost ($)', 'Latency p50 (s)']
summary

,Accuracy based on judge of all 3 fields,Parse rate,Judge score,Total cost ($),Latency p50 (s)
strategy,,,,,
cot,3.5,1.0,3.370,0.001,1.591
few_shot,3.8,1.0,3.625,0.001,1.500
structured,4.0,1.0,3.800,0.001,1.435
zero_shot,3.5,1.0,3.385,0.001,1.740

In [17]:
df

,accuracy,groundedness,format,reasoning,strategy,snippet_id,cost_usd,latency,parse_status,llm_judge_score
0,4,4,4,The candidate's extracted result is fully accu...,zero_shot,j01,0.000063,2.376591,1,3.80
1,4,4,4,The candidate's extracted result is fully accu...,few_shot,j01,0.000099,1.637517,1,3.80
2,4,4,4,The candidate's extracted result matches the i...,structured,j01,0.000078,1.543426,1,3.80
3,4,4,4,The candidate's extracted result matches the i...,cot,j01,0.000077,1.551843,1,3.80
4,4,4,4,The candidate's extracted result matches the i...,zero_shot,j02,0.000071,1.632005,1,3.80
5,4,4,4,The candidate's extracted result matches the i...,few_shot,j02,0.000094,1.457990,1,3.80
6,4,4,4,The candidate's extracted result matches the i...,structured,j02,0.000077,1.979464,1,3.80
7,4,4,4,The candidate's extracted result matches the i...,cot,j02,0.000068,1.385971,1,3.80
8,4,4,4,The candidate's extracted result matches the i...,zero_shot,j03,0.000072,2.427495,1,3.80
9,4,4,4,The candidate's extracted result matches the i...,few_shot,j03,0.000096,1.624274,1,3.80
10,4,4,4,The candidate's extracted result matches the i...,structured,j03,0.000079,1.393043,1,3.80
11,4,4,4,The candidate's extracted result matches the i...,cot,j03,0.000079,2.144336,1,3.80
12,4,4,4,The candidate's extracted result matches the i...,zero_shot,j04,0.000076,1.596824,1,3.80
13,4,4,4,The candidate's extracted result matches the i...,few_shot,j04,0.000099,1.491147,1,3.80
14,4,4,4,The candidate's extracted result matches the i...,structured,j04,0.000082,1.418955,1,3.80
15,4,4,4,The candidate's extracted result matches the i...,cot,j04,0.000078,1.616465,1,3.80
16,4,4,4,The candidate's extracted result is fully accu...,zero_shot,j05,0.000073,1.915874,1,3.80
17,4,4,4,The candidate's extracted result is fully accu...,few_shot,j05,0.000100,1.558513,1,3.80
18,4,4,4,The candidate's extracted result is accurate a...,structured,j05,0.000076,1.425209,1,3.80
19,2,2,3,The candidate correctly identified the company...,cot,j05,0.000081,1.734035,1,2.05
20,3,3,4,The candidate's answer correctly identifies th...,zero_shot,j06,0.000076,1.648249,1,3.00
21,4,4,4,The candidate's extracted result is fully accu...,few_shot,j06,0.000094,1.432005,1,3.80
22,4,4,4,The candidate's extracted result matches the i...,structured,j06,0.000096,1.576538,1,3.80
23,3,3,4,The candidate's response correctly identifies ...,cot,j06,0.000084,1.611312,1,3.00
24,4,4,4,The candidate's extracted result matches the i...,zero_shot,j07,0.000065,1.831831,1,3.80
25,4,4,4,The candidate's extracted result is fully accu...,few_shot,j07,0.000098,1.509840,1,3.80
26,4,4,4,The candidate's extracted result is fully accu...,structured,j07,0.000081,1.387564,1,3.80
27,4,4,4,The candidate's extracted result matches the i...,cot,j07,0.000078,1.602471,1,3.80
28,4,4,4,The candidate's extracted result matches the i...,zero_shot,j08,0.000072,1.990169,1,3.80
29,4,4,4,The candidate's extracted result matches the i...,few_shot,j08,0.000094,1.455985,1,3.80
30,4,4,4,The candidate's extracted result matches the i...,structured,j08,0.000084,1.444414,1,3.80
31,4,4,4,The candidate's extracted result matches the i...,cot,j08,0.000073,1.556689,1,3.80
32,2,2,3,The candidate answer correctly identifies the ...,zero_shot,j09,0.000073,1.605160,1,2.05
33,2,2,3,The candidate correctly identified the company...,few_shot,j09,0.000097,1.481938,1,2.05
34,4,4,4,The candidate's extracted result is fully accu...,structured,j09,0.000082,1.390265,1,3.80
35,2,2,3,The candidate correctly identified the company...,cot,j09,0.000072,1.531198,1,2.05
36,2,2,4,The candidate answer correctly identifies the ...,zero_shot,j10,0.000074,1.599776,1,2.20
37,4,4,4,The candidate's extracted result matches the i...,few_shot,j10,0.000103,2.049278,1,3.80
38,4,4,4,The candidate's extracted result matches the i...,structured,j10,0.000085,1.456370,1,3.80
39,4,4,4,The candidate's extracted result is fully accu...,cot,j10,0.000085,1.580071,1,3.80

## Step 6 — Write your reflection

Open `mp1_writeup.md` and answer the four questions from the brief.

Then commit:

```bash
git add mp1/
git commit -m 'feat(mp1): prompt strategy comparison + writeup'
```